remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-architect
title: "Sassy Swifties - The Official Del Norte Taylor Swift Fan Club"
description: "A community with love and support for Taylor Swift"
gitorg: "https://github.com/jm1021/leuck_reunion"
