theme: jekyll-theme-midnight
title: "Sassy Swifties - The Official Del Norte Taylor Swift Fan Club"
description: "June 26 to July 1 2023"
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
